**13.	Найдите спектральное разложение матрицы A с помощью python. Используйте функцию numpy.linalg.eigh, которая поможет рассчитать собственные числа и векторы матрицы.**

$A = V ∙ Λ ∙ V^{-1} $

In [1]:
import numpy as np

def spectral_decomposition(matrix):

    #Найдем собственные значения и векторы матрицы
    eigenvalues, eigenvectors = np.linalg.eigh(matrix)
    
    print("Собственные значения:\n")
    for i, eigenvalue in enumerate(eigenvalues):
        print(f"λ{i+1} = {eigenvalue}\n")

    print("Собственные векторы:\n")
    for i, eigenvector in enumerate(eigenvectors.T):
        print(f"V{i+1} = {eigenvector}\n")
        
    #Собственные значения составляют диагональ матрицы лямбда
    lambda_matrix = np.diag(eigenvalues)
    
    #Собственные векторы составляют матрицу V и обратную V
    V_matrix = eigenvectors
    inv_V_matrix = np.linalg.inv(V_matrix)
    
    #Проверим, что произведение компонент разложения равно исходной матрице
    temp = np.dot(V_matrix, lambda_matrix)
    result = np.dot(temp, inv_V_matrix)
    
    print('Произведение компонент разложения: \n')
    print(result)

In [2]:
A = np.array([[1., 3., 4.],
              [3., 3., 1.],
              [4., 1., 2.]])

spectral_decomposition(A)

Собственные значения:

λ1 = -3.020699255079208

λ2 = 1.6652777053317827

λ3 = 7.355421549747427

Собственные векторы:

V1 = [ 0.77532334 -0.2934401  -0.55925542]

V2 = [ 0.1440438  -0.78000906  0.60896408]

V3 = [-0.61491877 -0.55270134 -0.562491  ]

Произведение компонент разложения: 

[[1. 3. 4.]
 [3. 3. 1.]
 [4. 1. 2.]]
