**14.	Найдите сингулярное разложение матрицы B c помощью python.**

$B = U ∙ Σ ∙ V^T$

In [1]:
import numpy as np

def singular_decomposition(matrix):
    
    # Найдем произведение исходной и сопряженно-транспонированной матрицы 
    AAT = np.dot(matrix, matrix.T)

    # Найдем собственные векторы и значения полученной матрицы
    eigenvalues, eigenvectors = np.linalg.eig(AAT)

    # Упорядочим собственные значения и векторы по убыванию
    sorted_indices = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_indices]
    eigenvectors = eigenvectors[:, sorted_indices]
    
    #Собственные векторы матрицы AAT будут являться левыми сингулярными векторами
    U = eigenvectors

    # Найдем произведение сопряженно-транспонированной и исходной матрицы 
    ATA = np.dot(matrix.T, matrix)

    eigenvalues, eigenvectors = np.linalg.eig(ATA)

    sorted_indices = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_indices]
    eigenvectors = eigenvectors[:, sorted_indices]

    #Собственные векторы матрицы ATА будут являться правыми сингулярными векторами
    V = eigenvectors.T
    
    #Корни собственных значений матрицы ATА будут являться сингулярными значениями матрицы
    S = np.sqrt(eigenvalues)

    # Вывод результатов
    print("Матрица U:")
    print(U)
    print("Диагональ матрицы Lambda:")
    print(S)
    print("Матрица V:")
    print(V)

In [2]:
B = np.array([[1., 3., 8.],
             [4., 2., 0.],
             [7., 1., 9.]])

singular_decomposition(B)

Матрица U:
[[-0.56375011 -0.66253408 -0.49318799]
 [-0.1711562   0.67786769 -0.71498318]
 [-0.80801693  0.31865967  0.4955448 ]]
Диагональ матрицы Lambda:
[13.94868243  4.93243763  2.4708941 ]
Матрица V:
[[ 0.49499252  0.20371671  0.84467858]
 [ 0.86763476 -0.06349948 -0.49313055]
 [ 0.04682228 -0.97696843  0.20818346]]


In [3]:
#Сравним результат с готовой версией сингулярного разложения из Numpy
np.linalg.svd(B)

(array([[-0.56375011,  0.66253408, -0.49318799],
        [-0.1711562 , -0.67786769, -0.71498318],
        [-0.80801693, -0.31865967,  0.4955448 ]]),
 array([13.94868243,  4.93243763,  2.4708941 ]),
 array([[-0.49499252, -0.20371671, -0.84467858],
        [-0.86763476,  0.06349948,  0.49313055],
        [ 0.04682228, -0.97696843,  0.20818346]]))