In [2]:
import numpy as np

In [22]:
def svd(matrix: np.ndarray):
    U, S, Vh = np.linalg.svd(matrix)
    
    print('Матрица левых сингулярных векторов:')
    for i in range(U.shape[1]):
        print(U[:, i])

    print('\nСингулярные числа:')
    for i in range(S.shape[0]):
        print(S[i])

    print('\nМатрица правых сингулярных векторов:')
    for i in range(Vh.shape[0]):
        print(Vh[i])

    print('\nПроверка:')
    print(np.round(np.dot(U, np.dot(np.diag(S), Vh)), 3))




In [10]:
mat_A = np.array([[1, 3, 8], [4, 2, 0], [7, 1, 9]])

In [23]:
svd(mat_A)

Матрица левых сингулярных векторов:
[-0.56375011 -0.1711562  -0.80801693]
[ 0.66253408 -0.67786769 -0.31865967]
[-0.49318799 -0.71498318  0.4955448 ]

Сингулярные числа:
13.9486824255103
4.932437625344551
2.4708941022119117

Матрица правых сингулярных векторов:
[-0.49499252 -0.20371671 -0.84467858]
[-0.86763476  0.06349948  0.49313055]
[ 0.04682228 -0.97696843  0.20818346]

Проверка:
[[1. 3. 8.]
 [4. 2. 0.]
 [7. 1. 9.]]
