In [5]:
import numpy as np

In [24]:
def spectral_decomposition(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    
    print('Собственные значения матрицы:')
    for i in range(len(eigenvalues)):
        print(f'λ{i+1} = {eigenvalues[i]}')

    print('\nСобственные векторы матрицы:')
    for i in range(len(eigenvectors)):
        print(f'v{i+1} = {eigenvectors[i]}')
        


    print('\nИсходная матрица через собственные значения и векторы:')
    print(np.dot(np.dot(eigenvectors, np.diag(eigenvalues)), np.linalg.inv(eigenvectors)))

    
    

In [25]:
mat_A = np.array([[1, 3, 4], [3, 3, 1], [4, 1, 2]])

In [26]:
spectral_decomposition(mat_A)

Собственные значения матрицы:
λ1 = 7.355421549747428
λ2 = -3.020699255079209
λ3 = 1.665277705331783

Собственные векторы матрицы:
v1 = [-0.61491877 -0.77532334  0.1440438 ]
v2 = [-0.55270134  0.2934401  -0.78000906]
v3 = [-0.562491    0.55925542  0.60896408]

Исходная матрица через собственные значения и векторы:
[[1. 3. 4.]
 [3. 3. 1.]
 [4. 1. 2.]]
